// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: score.proto

#include "score.pb.h"
#include "score.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace score {

static const char* ScoreService_method_names[] = {
  "/score.ScoreService/CalculateScore",
};

std::unique_ptr< ScoreService::Stub> ScoreService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ScoreService::Stub> stub(new ScoreService::Stub(channel, options));
  return stub;
}

ScoreService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CalculateScore_(ScoreService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ScoreService::Stub::CalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::score::CalculateScoreResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::score::CalculateScoreRequest, ::score::CalculateScoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CalculateScore_, context, request, response);
}

void ScoreService::Stub::async::CalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest* request, ::score::CalculateScoreResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::score::CalculateScoreRequest, ::score::CalculateScoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateScore_, context, request, response, std::move(f));
}

void ScoreService::Stub::async::CalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest* request, ::score::CalculateScoreResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateScore_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::score::CalculateScoreResponse>* ScoreService::Stub::PrepareAsyncCalculateScoreRaw(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::score::CalculateScoreResponse, ::score::CalculateScoreRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CalculateScore_, context, request);
}

::grpc::ClientAsyncResponseReader< ::score::CalculateScoreResponse>* ScoreService::Stub::AsyncCalculateScoreRaw(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCalculateScoreRaw(context, request, cq);
  result->StartCall();
  return result;
}

ScoreService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ScoreService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ScoreService::Service, ::score::CalculateScoreRequest, ::score::CalculateScoreResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ScoreService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::score::CalculateScoreRequest* req,
             ::score::CalculateScoreResponse* resp) {
               return service->CalculateScore(ctx, req, resp);
             }, this)));
}

ScoreService::Service::~Service() {
}

::grpc::Status ScoreService::Service::CalculateScore(::grpc::ServerContext* context, const ::score::CalculateScoreRequest* request, ::score::CalculateScoreResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace score

