// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: score.proto
#ifndef GRPC_score_2eproto__INCLUDED
#define GRPC_score_2eproto__INCLUDED

#include "score.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace score {

class ScoreService final {
 public:
  static constexpr char const* service_full_name() {
    return "score.ScoreService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::score::CalculateScoreResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::score::CalculateScoreResponse>> AsyncCalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::score::CalculateScoreResponse>>(AsyncCalculateScoreRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::score::CalculateScoreResponse>> PrepareAsyncCalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::score::CalculateScoreResponse>>(PrepareAsyncCalculateScoreRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest* request, ::score::CalculateScoreResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest* request, ::score::CalculateScoreResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::score::CalculateScoreResponse>* AsyncCalculateScoreRaw(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::score::CalculateScoreResponse>* PrepareAsyncCalculateScoreRaw(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::score::CalculateScoreResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::score::CalculateScoreResponse>> AsyncCalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::score::CalculateScoreResponse>>(AsyncCalculateScoreRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::score::CalculateScoreResponse>> PrepareAsyncCalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::score::CalculateScoreResponse>>(PrepareAsyncCalculateScoreRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest* request, ::score::CalculateScoreResponse* response, std::function<void(::grpc::Status)>) override;
      void CalculateScore(::grpc::ClientContext* context, const ::score::CalculateScoreRequest* request, ::score::CalculateScoreResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::score::CalculateScoreResponse>* AsyncCalculateScoreRaw(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::score::CalculateScoreResponse>* PrepareAsyncCalculateScoreRaw(::grpc::ClientContext* context, const ::score::CalculateScoreRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CalculateScore_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CalculateScore(::grpc::ServerContext* context, const ::score::CalculateScoreRequest* request, ::score::CalculateScoreResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CalculateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CalculateScore() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CalculateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateScore(::grpc::ServerContext* /*context*/, const ::score::CalculateScoreRequest* /*request*/, ::score::CalculateScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculateScore(::grpc::ServerContext* context, ::score::CalculateScoreRequest* request, ::grpc::ServerAsyncResponseWriter< ::score::CalculateScoreResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CalculateScore<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CalculateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CalculateScore() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::score::CalculateScoreRequest, ::score::CalculateScoreResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::score::CalculateScoreRequest* request, ::score::CalculateScoreResponse* response) { return this->CalculateScore(context, request, response); }));}
    void SetMessageAllocatorFor_CalculateScore(
        ::grpc::MessageAllocator< ::score::CalculateScoreRequest, ::score::CalculateScoreResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::score::CalculateScoreRequest, ::score::CalculateScoreResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CalculateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateScore(::grpc::ServerContext* /*context*/, const ::score::CalculateScoreRequest* /*request*/, ::score::CalculateScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculateScore(
      ::grpc::CallbackServerContext* /*context*/, const ::score::CalculateScoreRequest* /*request*/, ::score::CalculateScoreResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CalculateScore<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CalculateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CalculateScore() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CalculateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateScore(::grpc::ServerContext* /*context*/, const ::score::CalculateScoreRequest* /*request*/, ::score::CalculateScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CalculateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CalculateScore() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CalculateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateScore(::grpc::ServerContext* /*context*/, const ::score::CalculateScoreRequest* /*request*/, ::score::CalculateScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculateScore(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CalculateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CalculateScore() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CalculateScore(context, request, response); }));
    }
    ~WithRawCallbackMethod_CalculateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateScore(::grpc::ServerContext* /*context*/, const ::score::CalculateScoreRequest* /*request*/, ::score::CalculateScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculateScore(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CalculateScore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CalculateScore() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::score::CalculateScoreRequest, ::score::CalculateScoreResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::score::CalculateScoreRequest, ::score::CalculateScoreResponse>* streamer) {
                       return this->StreamedCalculateScore(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CalculateScore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CalculateScore(::grpc::ServerContext* /*context*/, const ::score::CalculateScoreRequest* /*request*/, ::score::CalculateScoreResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCalculateScore(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::score::CalculateScoreRequest,::score::CalculateScoreResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CalculateScore<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CalculateScore<Service > StreamedService;
};

}  // namespace score


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_score_2eproto__INCLUDED
