// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: score.proto
// Protobuf C++ Version: 5.29.3

#include "score.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace score {

inline constexpr CalculateScoreResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : final_score_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CalculateScoreResponse::CalculateScoreResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CalculateScoreResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CalculateScoreResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CalculateScoreResponseDefaultTypeInternal() {}
  union {
    CalculateScoreResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CalculateScoreResponseDefaultTypeInternal _CalculateScoreResponse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR CalculateScoreRequest_ScoresEntry_DoNotUse::CalculateScoreRequest_ScoresEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : CalculateScoreRequest_ScoresEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : CalculateScoreRequest_ScoresEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CalculateScoreRequest_ScoresEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CalculateScoreRequest_ScoresEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CalculateScoreRequest_ScoresEntry_DoNotUseDefaultTypeInternal() {}
  union {
    CalculateScoreRequest_ScoresEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CalculateScoreRequest_ScoresEntry_DoNotUseDefaultTypeInternal _CalculateScoreRequest_ScoresEntry_DoNotUse_default_instance_;

inline constexpr CalculateScoreRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : scores_{},
        team_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CalculateScoreRequest::CalculateScoreRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CalculateScoreRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CalculateScoreRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CalculateScoreRequestDefaultTypeInternal() {}
  union {
    CalculateScoreRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CalculateScoreRequestDefaultTypeInternal _CalculateScoreRequest_default_instance_;
}  // namespace score
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_score_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_score_2eproto = nullptr;
const ::uint32_t
    TableStruct_score_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::score::CalculateScoreRequest_ScoresEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::score::CalculateScoreRequest_ScoresEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::score::CalculateScoreRequest_ScoresEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::score::CalculateScoreRequest_ScoresEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::score::CalculateScoreRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::score::CalculateScoreRequest, _impl_.team_id_),
        PROTOBUF_FIELD_OFFSET(::score::CalculateScoreRequest, _impl_.scores_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::score::CalculateScoreResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::score::CalculateScoreResponse, _impl_.final_score_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::score::CalculateScoreRequest_ScoresEntry_DoNotUse)},
        {12, -1, -1, sizeof(::score::CalculateScoreRequest)},
        {22, -1, -1, sizeof(::score::CalculateScoreResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::score::_CalculateScoreRequest_ScoresEntry_DoNotUse_default_instance_._instance,
    &::score::_CalculateScoreRequest_default_instance_._instance,
    &::score::_CalculateScoreResponse_default_instance_._instance,
};
const char descriptor_table_protodef_score_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013score.proto\022\005score\"\221\001\n\025CalculateScoreR"
    "equest\022\017\n\007team_id\030\001 \001(\t\0228\n\006scores\030\002 \003(\0132"
    "(.score.CalculateScoreRequest.ScoresEntr"
    "y\032-\n\013ScoresEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002"
    " \001(\005:\0028\001\"-\n\026CalculateScoreResponse\022\023\n\013fi"
    "nal_score\030\001 \001(\0052]\n\014ScoreService\022M\n\016Calcu"
    "lateScore\022\034.score.CalculateScoreRequest\032"
    "\035.score.CalculateScoreResponseB!\n\023com.te"
    "amhealth.grpcB\nScoreProtob\006proto3"
};
static ::absl::once_flag descriptor_table_score_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_score_2eproto = {
    false,
    false,
    353,
    descriptor_table_protodef_score_2eproto,
    "score.proto",
    &descriptor_table_score_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_score_2eproto::offsets,
    file_level_enum_descriptors_score_2eproto,
    file_level_service_descriptors_score_2eproto,
};
namespace score {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              CalculateScoreRequest_ScoresEntry_DoNotUse::CalculateScoreRequest_ScoresEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              CalculateScoreRequest_ScoresEntry_DoNotUse::CalculateScoreRequest_ScoresEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              CalculateScoreRequest_ScoresEntry_DoNotUse::CalculateScoreRequest_ScoresEntry_DoNotUse() : SuperType() {}
              CalculateScoreRequest_ScoresEntry_DoNotUse::CalculateScoreRequest_ScoresEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* CalculateScoreRequest_ScoresEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) CalculateScoreRequest_ScoresEntry_DoNotUse(arena);
              }
              constexpr auto CalculateScoreRequest_ScoresEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CalculateScoreRequest_ScoresEntry_DoNotUse),
                                                          alignof(CalculateScoreRequest_ScoresEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull CalculateScoreRequest_ScoresEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_CalculateScoreRequest_ScoresEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &CalculateScoreRequest_ScoresEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<CalculateScoreRequest_ScoresEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &CalculateScoreRequest_ScoresEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &CalculateScoreRequest_ScoresEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(CalculateScoreRequest_ScoresEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &CalculateScoreRequest_ScoresEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_score_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* CalculateScoreRequest_ScoresEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 51, 2> CalculateScoreRequest_ScoresEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CalculateScoreRequest_ScoresEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::score::CalculateScoreRequest_ScoresEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CalculateScoreRequest_ScoresEntry_DoNotUse, _impl_.value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(CalculateScoreRequest_ScoresEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CalculateScoreRequest_ScoresEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(CalculateScoreRequest_ScoresEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 value = 2;
    {PROTOBUF_FIELD_OFFSET(CalculateScoreRequest_ScoresEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\47\3\0\0\0\0\0\0"
    "score.CalculateScoreRequest.ScoresEntry"
    "key"
  }},
};

// ===================================================================

class CalculateScoreRequest::_Internal {
 public:
};

CalculateScoreRequest::CalculateScoreRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:score.CalculateScoreRequest)
}
inline PROTOBUF_NDEBUG_INLINE CalculateScoreRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::score::CalculateScoreRequest& from_msg)
      : scores_{visibility, arena, from.scores_},
        team_id_(arena, from.team_id_),
        _cached_size_{0} {}

CalculateScoreRequest::CalculateScoreRequest(
    ::google::protobuf::Arena* arena,
    const CalculateScoreRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CalculateScoreRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:score.CalculateScoreRequest)
}
inline PROTOBUF_NDEBUG_INLINE CalculateScoreRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : scores_{visibility, arena},
        team_id_(arena),
        _cached_size_{0} {}

inline void CalculateScoreRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CalculateScoreRequest::~CalculateScoreRequest() {
  // @@protoc_insertion_point(destructor:score.CalculateScoreRequest)
  SharedDtor(*this);
}
inline void CalculateScoreRequest::SharedDtor(MessageLite& self) {
  CalculateScoreRequest& this_ = static_cast<CalculateScoreRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.team_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CalculateScoreRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CalculateScoreRequest(arena);
}
constexpr auto CalculateScoreRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CalculateScoreRequest, _impl_.scores_) +
          decltype(CalculateScoreRequest::_impl_.scores_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(CalculateScoreRequest, _impl_.scores_) +
          decltype(CalculateScoreRequest::_impl_.scores_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(CalculateScoreRequest), alignof(CalculateScoreRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CalculateScoreRequest::PlacementNew_,
                                 sizeof(CalculateScoreRequest),
                                 alignof(CalculateScoreRequest));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CalculateScoreRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CalculateScoreRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CalculateScoreRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CalculateScoreRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CalculateScoreRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CalculateScoreRequest>(), &CalculateScoreRequest::ByteSizeLong,
            &CalculateScoreRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CalculateScoreRequest, _impl_._cached_size_),
        false,
    },
    &CalculateScoreRequest::kDescriptorMethods,
    &descriptor_table_score_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CalculateScoreRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 1, 49, 2> CalculateScoreRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::score::CalculateScoreRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string team_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CalculateScoreRequest, _impl_.team_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string team_id = 1;
    {PROTOBUF_FIELD_OFFSET(CalculateScoreRequest, _impl_.team_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // map<string, int32> scores = 2;
    {PROTOBUF_FIELD_OFFSET(CalculateScoreRequest, _impl_.scores_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(CalculateScoreRequest()._impl_.scores_)>(
        1, 0, 0, 9,
        5)},
  }}, {{
    "\33\7\6\0\0\0\0\0"
    "score.CalculateScoreRequest"
    "team_id"
    "scores"
  }},
};

PROTOBUF_NOINLINE void CalculateScoreRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:score.CalculateScoreRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.scores_.Clear();
  _impl_.team_id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CalculateScoreRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CalculateScoreRequest& this_ = static_cast<const CalculateScoreRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CalculateScoreRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CalculateScoreRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:score.CalculateScoreRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string team_id = 1;
          if (!this_._internal_team_id().empty()) {
            const std::string& _s = this_._internal_team_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "score.CalculateScoreRequest.team_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // map<string, int32> scores = 2;
          if (!this_._internal_scores().empty()) {
            using MapType = ::google::protobuf::Map<std::string, ::int32_t>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, ::int32_t,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_INT32>;
            const auto& field = this_._internal_scores();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "score.CalculateScoreRequest.scores");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    2, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "score.CalculateScoreRequest.scores");
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:score.CalculateScoreRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CalculateScoreRequest::ByteSizeLong(const MessageLite& base) {
          const CalculateScoreRequest& this_ = static_cast<const CalculateScoreRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CalculateScoreRequest::ByteSizeLong() const {
          const CalculateScoreRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:score.CalculateScoreRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<string, int32> scores = 2;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_scores_size());
              for (const auto& entry : this_._internal_scores()) {
                total_size += _pbi::MapEntryFuncs<std::string, ::int32_t,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_INT32>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // string team_id = 1;
            if (!this_._internal_team_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_team_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CalculateScoreRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CalculateScoreRequest*>(&to_msg);
  auto& from = static_cast<const CalculateScoreRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:score.CalculateScoreRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.scores_.MergeFrom(from._impl_.scores_);
  if (!from._internal_team_id().empty()) {
    _this->_internal_set_team_id(from._internal_team_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CalculateScoreRequest::CopyFrom(const CalculateScoreRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:score.CalculateScoreRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CalculateScoreRequest::InternalSwap(CalculateScoreRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.scores_.InternalSwap(&other->_impl_.scores_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.team_id_, &other->_impl_.team_id_, arena);
}

::google::protobuf::Metadata CalculateScoreRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CalculateScoreResponse::_Internal {
 public:
};

CalculateScoreResponse::CalculateScoreResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:score.CalculateScoreResponse)
}
CalculateScoreResponse::CalculateScoreResponse(
    ::google::protobuf::Arena* arena, const CalculateScoreResponse& from)
    : CalculateScoreResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CalculateScoreResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CalculateScoreResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.final_score_ = {};
}
CalculateScoreResponse::~CalculateScoreResponse() {
  // @@protoc_insertion_point(destructor:score.CalculateScoreResponse)
  SharedDtor(*this);
}
inline void CalculateScoreResponse::SharedDtor(MessageLite& self) {
  CalculateScoreResponse& this_ = static_cast<CalculateScoreResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* CalculateScoreResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CalculateScoreResponse(arena);
}
constexpr auto CalculateScoreResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CalculateScoreResponse),
                                            alignof(CalculateScoreResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CalculateScoreResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CalculateScoreResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CalculateScoreResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CalculateScoreResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CalculateScoreResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CalculateScoreResponse>(), &CalculateScoreResponse::ByteSizeLong,
            &CalculateScoreResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CalculateScoreResponse, _impl_._cached_size_),
        false,
    },
    &CalculateScoreResponse::kDescriptorMethods,
    &descriptor_table_score_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CalculateScoreResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CalculateScoreResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::score::CalculateScoreResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 final_score = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CalculateScoreResponse, _impl_.final_score_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CalculateScoreResponse, _impl_.final_score_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 final_score = 1;
    {PROTOBUF_FIELD_OFFSET(CalculateScoreResponse, _impl_.final_score_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void CalculateScoreResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:score.CalculateScoreResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.final_score_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CalculateScoreResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CalculateScoreResponse& this_ = static_cast<const CalculateScoreResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CalculateScoreResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CalculateScoreResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:score.CalculateScoreResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 final_score = 1;
          if (this_._internal_final_score() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_final_score(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:score.CalculateScoreResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CalculateScoreResponse::ByteSizeLong(const MessageLite& base) {
          const CalculateScoreResponse& this_ = static_cast<const CalculateScoreResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CalculateScoreResponse::ByteSizeLong() const {
          const CalculateScoreResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:score.CalculateScoreResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 final_score = 1;
            if (this_._internal_final_score() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_final_score());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CalculateScoreResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CalculateScoreResponse*>(&to_msg);
  auto& from = static_cast<const CalculateScoreResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:score.CalculateScoreResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_final_score() != 0) {
    _this->_impl_.final_score_ = from._impl_.final_score_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CalculateScoreResponse::CopyFrom(const CalculateScoreResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:score.CalculateScoreResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CalculateScoreResponse::InternalSwap(CalculateScoreResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.final_score_, other->_impl_.final_score_);
}

::google::protobuf::Metadata CalculateScoreResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace score
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_score_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
